name: MBank
version: '3.1'
main: com.chkaduuu.mcbank.McBank
api-version: '26.1'
authors: [Chkaduuu]
description: A bank plugin with GUI, accounts, loans, transfers, ATM and advanced features

softdepend:
  - PlaceholderAPI
  - Vault
  - EssentialsX
  - CMI

commands:
  mcbank:
    description: Main McBank command
    usage: /<command> [subcommand]
    aliases: [bank]
    permission: mcbank.use

permissions:
  mcbank.use:
    description: Allows basic McBank usage
    default: true
  mcbank.admin:
    description: Allows admin McBank commands
    default: op
  mcbank.atm.set:
    description: Allows placing ATM machines
    default: op
  mcbank.*:
    description: All McBank permissions
    default: op
    children:
      mcbank.use: true
      mcbank.admin: true
      mcbank.atm.set: true
